Traceback (most recent call last):
  File "/home/timothyelder/mag/scripts/direct_filter_mag.py", line 19, in <module>
    faculty_df_complete = pd.read_csv("/home/timothyelder/Documents/data/faculty_df_complete.csv")
  File "/home/timothyelder/.conda/envs/soc_of_soc/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/timothyelder/.conda/envs/soc_of_soc/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/timothyelder/.conda/envs/soc_of_soc/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/timothyelder/.conda/envs/soc_of_soc/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/timothyelder/.conda/envs/soc_of_soc/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/timothyelder/.conda/envs/soc_of_soc/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/timothyelder/.conda/envs/soc_of_soc/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/timothyelder/.conda/envs/soc_of_soc/lib/python3.7/site-packages/pandas/io/common.py", line 706, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/home/timothyelder/Documents/data/faculty_df_complete.csv'
